WIP: Dev gms
umati/Sample-Server pull request #659
Opened 2022-03-18 08:49 UTC by Kantiran91

Add Sample Machine for GMS Release Candidate.

2022-03-18 09:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/umati/Sample-Server?pullRequest=659) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/umati/Sample-Server?pullRequest=659) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: GoetzGoerisch<br/>:x: Kantiran91<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/umati/Sample-Server?pullRequest=659) it.</sub>

2022-03-23 13:53 UTC, GoetzGoerisch requested changes

2022-03-23 13:53 UTC, GoetzGoerisch commented on TypeDefinition/GMS/GMSEquipmentType.hpp
> + */
Add copyright note.

2022-03-23 13:53 UTC, GoetzGoerisch commented on TypeDefinition/MachineryResult/Constants.hpp
> + */
Add copyright note.

2022-03-23 13:53 UTC, GoetzGoerisch commented on model/GMS/Opc.Ua.MachineryResult.NodeSet2.xml
> +<?xml version="1.0" encoding="utf-8"?>
Add license header

2022-03-23 13:53 UTC, GoetzGoerisch commented on model/GMS/opc.ua.gms.nodeset2.xml
> +<?xml version="1.0" encoding="utf-8"?>
Add license header

2022-03-23 13:53 UTC, GoetzGoerisch commented on CMakeLists.txt
> +ua_generate_nodeset_and_datatypes(
Add copyright note to header

2022-03-28 10:32 UTC, Kantiran91 commented on TypeDefinition/MachineryResult/Constants.hpp
> + */
done

2022-03-28 10:32 UTC, Kantiran91 commented on CMakeLists.txt
> +ua_generate_nodeset_and_datatypes(
done

2022-03-28 10:32 UTC, Kantiran91 commented on TypeDefinition/GMS/GMSEquipmentType.hpp
> + */
done

2022-03-28 10:42 UTC, Kantiran91 commented on model/GMS/opc.ua.gms.nodeset2.xml
> +<?xml version="1.0" encoding="utf-8"?>
done

2022-03-28 10:43 UTC, Kantiran91 commented on model/GMS/Opc.Ua.MachineryResult.NodeSet2.xml
> +<?xml version="1.0" encoding="utf-8"?>
done

2022-03-31 11:13 UTC, GoetzGoerisch approved these changes

2022-03-31 11:15 UTC, GoetzGoerisch commented
Waiting for the upstream fix of deps/open62541 to be merged.

2022-04-20 14:14 UTC, GoetzGoerisch commented
@Kantiran91 @karstenroethig  upstream fix is included into `develop` branch.
Rebased and cleanup this branch. Please give it a review before we merge?

2022-04-21 09:07 UTC, karstenroethig commented
Looks good. Tested with newest Docker image.

I just added [adba8bf](https://github.com/umati/Sample-Server/pull/659/commits/adba8bf5f9dbdabe115a5ecc689ac0f4683ec4b5) to append the os name to the uploaded artifacts

2022-04-21 09:08 UTC, karstenroethig approved these changes

2022-04-22 05:41 UTC, merged