Draft: Add additive manufacturing model and sample server
umati/Sample-Server pull request #907
Opened 2022-10-18 11:33 UTC by kpm-berlin

Work in progress

2022-10-18 11:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/umati/Sample-Server?pullRequest=907) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/umati/Sample-Server?pullRequest=907) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/umati/Sample-Server?pullRequest=907) it.</sub>

2022-10-26 11:11 UTC, ccvca requested changes
Just some comments, as the project does not build at the moment.

2022-10-26 11:11 UTC, ccvca commented on TypeDefinition/AdditiveManufacturing/AdditiveManufacturing.hpp
> +    constants::NsGMSUri, UA_ADDITIVEMANUFACTURINGID_ADDITIVEMANUFACTURING)))  // FIXME: Check NodeId() parameters for correctness
GMS-Uri does not look right here. This sould be `NsAMUri`

2022-10-26 11:11 UTC, ccvca commented on TypeDefinition/AdditiveManufacturing/ConsumableList.hpp
> +REFL_END
A new line at the end of each file would be nice. (Otherwise these last lines appear edited, when something is edited in the file.)

2022-10-26 11:11 UTC, ccvca commented on model/AdditiveManufacturing/Opc.Ua.AdditiveManufacturing.Nodeset2.xml
> +        <Uri>http://yourorganisation.org/Opc.Ua.AdditiveManufacturing.NodeSet2/</Uri>
This does not look right. In the constant files, the namespace is named: `http://opcfoundation.org/AdditiveManufacturing/`

I would guess that the final URI might be `http://opcfoundation.org/UA/AdditiveManufacturing/` or `http://opcfoundation.org/UA/AM/`

2022-10-26 11:11 UTC, ccvca commented on TypeDefinition/AdditiveManufacturing/Consumable.hpp
> +struct Material_t {
File name does not match type name.

2022-10-28 15:36 UTC, Tradias approved these changes

2022-10-31 09:56 UTC, GoetzGoerisch approved these changes
Thank you for your contribution.

2022-10-31 09:57 UTC, GoetzGoerisch commented
@ccvca could you please give it a final look?

2022-10-31 10:09 UTC, ccvca reviewed
Looks good, just some questions about the Enum and other Fixme-comments.

2022-10-31 10:09 UTC, ccvca commented on TypeDefinition/AdditiveManufacturing/Consumable.hpp
> +    UmatiServerLib::constexp::NodeId(constants::NsAMUri, UA_ADDITIVEMANUFACTURINGID_CONSUMABLETYPE_EXTERNALIDENTIFIER)),  // FIXME: Wrong LIST type
`FIXME`
Is this intended?

2022-10-31 10:09 UTC, ccvca commented on TypeDefinition/AdditiveManufacturing/Consumable.hpp
> +    UmatiServerLib::constexp::NodeId(constants::NsAMUri, UA_ADDITIVEMANUFACTURINGID_CONSUMABLETYPE_IDENTIFIER)),  // FIXME: Wrong LIST type
`FIXME`

2022-10-31 10:09 UTC, ccvca commented on TypeDefinition/AdditiveManufacturing/Material.hpp
> +  BindableMemberValue<std::string> Function;  // FIXME: Add enum MaterialFunction
See https://github.com/umati/Sample-Server/blob/5b0082cd0e950fb36755ebe9989121531c23388b/TypeDefinition/IA/StackElementLight.hpp#L20 on how to use Enums.

2022-10-31 11:09 UTC, kpm-berlin commented on TypeDefinition/AdditiveManufacturing/Consumable.hpp
> +    UmatiServerLib::constexp::NodeId(constants::NsAMUri, UA_ADDITIVEMANUFACTURINGID_CONSUMABLETYPE_EXTERNALIDENTIFIER)),  // FIXME: Wrong LIST type
no, we missed this. Removed.

2022-10-31 12:15 UTC, ccvca approved these changes

2022-10-31 12:46 UTC, kpm-berlin commented
@GoetzGoerisch Is the location tag correct now? See [https://github.com/umati/Sample-Server/pull/907/commits/1b7a7c1dedba2810d40bdda5f9324ca10d104db2](https://github.com/umati/Sample-Server/pull/907/commits/1b7a7c1dedba2810d40bdda5f9324ca10d104db2)

2022-11-01 13:38 UTC, kpm-berlin commented
confirmed latest changes in UA Expert: 
![uaexpert-am-sample-server](https://user-images.githubusercontent.com/72387574/199246569-f45cab8c-51ac-45b5-a100-41a649ed7e2c.png)

2022-11-01 13:56 UTC, merged